package co.simplon.soninkrala.entities;

import jakarta.persistence.*;

import java.util.Set;

@Entity
@Table(name = "t_quiz")
public class QuizEntity {
    @Id
    @Column(name ="id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "quiz_name")
    private String quizName;

    @Column(name = "description")
    private String description;

    @ManyToMany
    @JoinTable(name = "t_questions_t_quiz",
    joinColumns = @JoinColumn(name = "id_quiz"),
    inverseJoinColumns = @JoinColumn(name = "id_question"))
    private Set<QuestionEntity> questions;

    public QuizEntity(){}

    private void setId(Integer id) {
        //generated by db
    }

    public Integer getId() {
        return id;
    }

    public String getQuizName() {
        return quizName;
    }

    public void setQuizName(String quizName) {
        this.quizName = quizName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<QuestionEntity> getQuestions() {
        return questions;
    }

    public void setQuestions(Set<QuestionEntity> questions) {
        this.questions = questions;
    }

    @Override
    public String toString() {
        return "QuizEntity{" +
                "id=" + id +
                ", quizName='" + quizName + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}
